import type { MenuItem } from '../types'

export const featuredMenu: MenuItem[] = [
  {
    id: '1',
    name: 'Truffle Mushroom Pasta',
    description: 'Silky pasta, roasted mushrooms, parmesan cream sauce.',
    price: '$18',
    tag: 'Pasta',
    category: 'Pasta',
    image: 'https://source.unsplash.com/1200x800/?truffle,pasta',
    rating: 4.9,
    availability: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Charred Salmon Bowl',
    description: 'Fresh salmon, citrus glaze, quinoa and seasonal greens.',
    price: '$22',
    tag: 'Main',
    category: 'Main Course',
    image: 'https://source.unsplash.com/1200x800/?salmon,bowl',
    rating: 4.8,
    availability: true,
    featured: true,
  },
  {
    id: '3',
    name: 'Dark Chocolate Lava Cake',
    description: 'Warm center, berry compote, and almond crumble.',
    price: '$10',
    tag: 'Dessert',
    category: 'Desserts',
    image: 'https://source.unsplash.com/1200x800/?lava,cake,chocolate',
    rating: 4.7,
    availability: true,
    featured: false,
  },
  {
    id: '7',
    name: 'Bruschetta',
    description: 'Toasted sourdough, heirloom tomato, basil oil, aged pecorino.',
    price: '$9',
    tag: 'Starter',
    category: 'Starters',
    image: 'https://source.unsplash.com/1200x800/?bruschetta',
    rating: 4.6,
    availability: true,
    featured: false,
  },
  {
    id: '8',
    name: 'Garlic Bread Supreme',
    description: 'House-baked ciabatta, roasted garlic butter, parsley, sea salt.',
    price: '$8',
    tag: 'Starter',
    category: 'Starters',
    image: 'https://source.unsplash.com/1200x800/?garlic,bread',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '9',
    name: 'Crispy Calamari',
    description: 'Lightly fried calamari, lemon aioli, caper dust.',
    price: '$13',
    tag: 'Starter',
    category: 'Starters',
    image: 'https://source.unsplash.com/1200x800/?calamari',
    rating: 4.6,
    availability: true,
    featured: false,
  },
  {
    id: '10',
    name: 'Stuffed Mushrooms',
    description: 'Baked mushrooms, garlic-herb ricotta, toasted breadcrumbs.',
    price: '$11',
    tag: 'Starter',
    category: 'Starters',
    image: 'https://source.unsplash.com/1200x800/?stuffed,mushroom',
    rating: 4.6,
    availability: true,
    featured: false,
  },
  {
    id: '11',
    name: 'Tomato Basil Soup',
    description: 'Slow-roasted tomato, fresh basil, cream swirl, garlic crouton.',
    price: '$9',
    tag: 'Soup',
    category: 'Soups',
    image: 'https://source.unsplash.com/1200x800/?tomato,soup',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '12',
    name: 'Cream of Mushroom Soup',
    description: 'Silky mushroom velouté, truffle oil finish, chive.',
    price: '$10',
    tag: 'Soup',
    category: 'Soups',
    image: 'https://source.unsplash.com/1200x800/?mushroom,soup',
    rating: 4.6,
    availability: true,
    featured: false,
  },
  {
    id: '13',
    name: 'Sweet Corn Soup',
    description: 'Velvety corn broth, charred corn kernels, coriander oil.',
    price: '$8',
    tag: 'Soup',
    category: 'Soups',
    image: 'https://source.unsplash.com/1200x800/?corn,soup',
    rating: 4.4,
    availability: true,
    featured: false,
  },
]

export const popularDishes: MenuItem[] = [
  {
    id: '4',
    name: 'Herb-Crusted Ribeye',
    description: 'Prime ribeye, herb crust, garlic butter, roasted seasonal vegetables.',
    price: '$28',
    tag: 'Main',
    category: 'Main Course',
    image: 'https://source.unsplash.com/1200x800/?ribeye,steak',
    rating: 4.8,
    availability: true,
    featured: false,
  },
  {
    id: '5',
    name: 'Seared Scallops',
    description: 'Dry-seared scallops, lemon-basil risotto, beurre blanc.',
    price: '$24',
    tag: 'Main',
    category: 'Main Course',
    image: 'https://source.unsplash.com/1200x800/?scallops',
    rating: 4.7,
    availability: true,
    featured: false,
  },
  {
    id: '6',
    name: 'Avocado Garden Salad',
    description: 'Mixed greens, citrus vinaigrette, avocado, toasted seeds.',
    price: '$12',
    tag: 'Salad',
    category: 'Salads',
    image: 'https://source.unsplash.com/1200x800/?avocado,salad',
    rating: 4.4,
    availability: true,
    featured: false,
  },
  {
    id: '14',
    name: 'Caesar Salad',
    description: 'Crisp romaine, shaved parmesan, house Caesar dressing, anchovy crumble.',
    price: '$11',
    tag: 'Salad',
    category: 'Salads',
    image: 'https://source.unsplash.com/1200x800/?caesar,salad',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '15',
    name: 'Greek Salad',
    description: 'Heirloom tomatoes, cucumber, kalamata olives, feta, oregano dressing.',
    price: '$12',
    tag: 'Salad',
    category: 'Salads',
    image: 'https://source.unsplash.com/1200x800/?greek,salad',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '16',
    name: 'Alfredo Pasta',
    description: 'Ribbon fettuccine, parmesan cream, cracked pepper.',
    price: '$16',
    tag: 'Pasta',
    category: 'Pasta',
    image: 'https://source.unsplash.com/1200x800/?alfredo,pasta',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '17',
    name: 'Arrabbiata Pasta',
    description: 'Penne in spicy San Marzano tomato sauce, basil, chili flakes.',
    price: '$15',
    tag: 'Pasta',
    category: 'Pasta',
    image: 'https://source.unsplash.com/1200x800/?arrabbiata,pasta',
    rating: 4.4,
    availability: true,
    featured: false,
  },
  {
    id: '18',
    name: 'Pesto Penne',
    description: 'Hand-pressed basil pesto, toasted pine nuts, pecorino.',
    price: '$15',
    tag: 'Pasta',
    category: 'Pasta',
    image: 'https://source.unsplash.com/1200x800/?pesto,penne',
    rating: 4.6,
    availability: true,
    featured: false,
  },
  {
    id: '19',
    name: 'Margherita Pizza',
    description: 'Wood-fired pizza, San Marzano tomato, fresh mozzarella, basil.',
    price: '$14',
    tag: 'Pizza',
    category: 'Pizza',
    image: 'https://source.unsplash.com/1200x800/?margherita,pizza',
    rating: 4.6,
    availability: true,
    featured: false,
  },
  {
    id: '20',
    name: 'Pepperoni Pizza',
    description: 'Crisp crust, house tomato sauce, premium pepperoni, smoked mozzarella.',
    price: '$15',
    tag: 'Pizza',
    category: 'Pizza',
    image: 'https://source.unsplash.com/1200x800/?pepperoni,pizza',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '21',
    name: 'Veggie Supreme Pizza',
    description: 'Roasted peppers, zucchini, mushrooms, red onion, basil oil.',
    price: '$16',
    tag: 'Pizza',
    category: 'Pizza',
    image: 'https://source.unsplash.com/1200x800/?vegetarian,pizza',
    rating: 4.4,
    availability: true,
    featured: false,
  },
  {
    id: '22',
    name: 'BBQ Chicken Pizza',
    description: 'Smoky BBQ glaze, roasted chicken, red onion, cilantro.',
    price: '$17',
    tag: 'Pizza',
    category: 'Pizza',
    image: 'https://source.unsplash.com/1200x800/?bbq,chicken,pizza',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '23',
    name: 'Grilled Chicken Steak',
    description: 'Herb-marinated chicken, char-grilled, roasted baby potatoes.',
    price: '$19',
    tag: 'Main',
    category: 'Main Course',
    image: 'https://source.unsplash.com/1200x800/?grilled,chicken',
    rating: 4.6,
    availability: true,
    featured: false,
  },
  {
    id: '24',
    name: 'Herb Crusted Lamb',
    description: 'Slow-roasted lamb, rosemary jus, dauphinoise potatoes.',
    price: '$32',
    tag: 'Main',
    category: 'Main Course',
    image: 'https://source.unsplash.com/1200x800/?lamb,chops',
    rating: 4.9,
    availability: true,
    featured: true,
  },
  {
    id: '25',
    name: 'Paneer Tikka Platter',
    description: 'Charred paneer, bell peppers, mint chutney, fragrant rice.',
    price: '$17',
    tag: 'Main',
    category: 'Main Course',
    image: 'https://source.unsplash.com/1200x800/?paneer,tikka',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '26',
    name: 'Veg Biryani',
    description: 'Aromatic basmati, roasted vegetables, saffron raita.',
    price: '$16',
    tag: 'Main',
    category: 'Main Course',
    image: 'https://source.unsplash.com/1200x800/?biryani',
    rating: 4.4,
    availability: true,
    featured: false,
  },
  {
    id: '27',
    name: 'Butter Chicken',
    description: 'Creamy tomato curry, tender chicken, steamed basmati.',
    price: '$18',
    tag: 'Main',
    category: 'Main Course',
    image: 'https://source.unsplash.com/1200x800/?butter,chicken',
    rating: 4.7,
    availability: true,
    featured: false,
  },
  {
    id: '28',
    name: 'Tiramisu',
    description: 'Mascarpone, espresso-soaked ladyfingers, cocoa dust.',
    price: '$11',
    tag: 'Dessert',
    category: 'Desserts',
    image: 'https://source.unsplash.com/1200x800/?tiramisu',
    rating: 4.6,
    availability: true,
    featured: false,
  },
  {
    id: '29',
    name: 'Cheesecake',
    description: 'Velvety cream cheese, graham crust, berry compote.',
    price: '$10',
    tag: 'Dessert',
    category: 'Desserts',
    image: 'https://source.unsplash.com/1200x800/?cheesecake',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '30',
    name: 'Brownie with Ice Cream',
    description: 'Warm fudge brownie, vanilla bean ice cream, salted caramel.',
    price: '$10',
    tag: 'Dessert',
    category: 'Desserts',
    image: 'https://source.unsplash.com/1200x800/?brownie,icecream',
    rating: 4.6,
    availability: true,
    featured: false,
  },
  {
    id: '31',
    name: 'Vanilla Panna Cotta',
    description: 'Silken panna cotta, citrus gel, pistachio crumble.',
    price: '$10',
    tag: 'Dessert',
    category: 'Desserts',
    image: 'https://source.unsplash.com/1200x800/?panna,cotta',
    rating: 4.4,
    availability: true,
    featured: false,
  },
  {
    id: '32',
    name: 'Fresh Lime Soda',
    description: 'Sparkling lime soda, mint, hint of cane sugar.',
    price: '$5',
    tag: 'Beverage',
    category: 'Beverages',
    image: 'https://source.unsplash.com/1200x800/?lime,soda',
    rating: 4.3,
    availability: true,
    featured: false,
  },
  {
    id: '33',
    name: 'Mango Smoothie',
    description: 'Ripe mango, Greek yogurt, honey, crushed ice.',
    price: '$6',
    tag: 'Beverage',
    category: 'Beverages',
    image: 'https://source.unsplash.com/1200x800/?mango,smoothie',
    rating: 4.5,
    availability: true,
    featured: false,
  },
  {
    id: '34',
    name: 'Cold Coffee',
    description: 'Chilled espresso, milk, light caramel swirls.',
    price: '$5',
    tag: 'Beverage',
    category: 'Beverages',
    image: 'https://source.unsplash.com/1200x800/?cold,coffee',
    rating: 4.4,
    availability: true,
    featured: false,
  },
  {
    id: '35',
    name: 'Cappuccino',
    description: 'Classic espresso with steamed milk and micro-foam.',
    price: '$4',
    tag: 'Beverage',
    category: 'Beverages',
    image: 'https://source.unsplash.com/1200x800/?cappuccino',
    rating: 4.4,
    availability: true,
    featured: false,
  },
  {
    id: '36',
    name: 'Green Tea',
    description: 'Delicate green tea, light floral aroma, served hot.',
    price: '$3',
    tag: 'Beverage',
    category: 'Beverages',
    image: 'https://source.unsplash.com/1200x800/?green,tea',
    rating: 4.3,
    availability: true,
    featured: false,
  },
  {
    id: '37',
    name: 'Fresh Orange Juice',
    description: 'Cold-pressed oranges, no sugar added, bright and refreshing.',
    price: '$5',
    tag: 'Beverage',
    category: 'Beverages',
    image: 'https://source.unsplash.com/1200x800/?orange,juice',
    rating: 4.4,
    availability: true,
    featured: false,
  },
]
